name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y gcc make valgrind cppcheck

    - name: Configure
      run: ./configure

    - name: Build Project
      run: make

    - name: Run Tests
      run: make check

    - name: Static Analysis
      run: cppcheck --enable=all --suppress=missingInclude src/

    - name: Run Distribution Check
      run: make distcheck

    - name: Memory Leak Check
      run: valgrind --leak-check=full ./bin/mv_project testfile.txt destdir/
